name: metview
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - backcall=0.1.0
  - bison=3.4
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - cairo=1.16.0
  - certifi=2019.11.28
  - curl=7.65.3
  - dbus=1.13.6
  - decorator=4.4.1
  - eccodes=2.14.1
  - expat=2.2.5
  - fftw=3.3.8
  - flex=2.6.4
  - fontconfig=2.13.1
  - freetype=2.10.0
  - fribidi=1.0.5
  - gdbm=1.18
  - gettext=0.19.8.1
  - glib=2.58.3
  - graphite2=1.3.13
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - harfbuzz=2.4.0
  - hdf4=4.2.13
  - hdf5=1.10.5
  - icu=64.2
  - ipykernel=5.1.3
  - ipython=7.10.1
  - ipython_genutils=0.2.0
  - jasper=1.900.1
  - jedi=0.15.1
  - jpeg=9c
  - jupyter_client=5.3.3
  - jupyter_core=4.6.1
  - krb5=1.16.3
  - libaec=1.0.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.0
  - libcurl=7.65.3
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm9=9.0.0
  - libnetcdf=4.6.2
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libsodium=1.0.17
  - libssh2=1.8.2
  - libstdcxx-ng=9.1.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxkbcommon=0.9.1
  - libxml2=2.9.10
  - m4=1.4.18
  - magics=4.2.0
  - magics-python=1.0.6
  - ncurses=6.1
  - nspr=4.23
  - nss=3.47
  - numpy=1.17.3
  - openssl=1.1.1d
  - pango=1.42.4
  - parso=0.5.1
  - pcre=8.43
  - pexpect=4.7.0
  - pip=19.3.1
  - pixman=0.38.0
  - proj4=6.1.1
  - prompt_toolkit=3.0.2
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pygments=2.5.2
  - python=3.7.3
  - python-dateutil=2.8.1
  - qt=5.12.5
  - readline=8.0
  - setuptools=41.6.0
  - simplejson=3.16.0
  - six=1.13.0
  - sqlite=3.30.1
  - tk=8.6.9
  - tornado=6.0.3
  - traitlets=4.3.3
  - wheel=0.33.6
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - zeromq=4.3.2
  - zlib=1.2.11
  - pip:
    - attrs==19.3.0
    - bleach==3.1.0
    - cffi==1.13.2
    - defusedxml==0.6.0
    - ecmwf-api-client==1.5.4
    - entrypoints==0.3
    - importlib-metadata==1.2.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jinja2==2.10.3
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==5.3.4
    - jupyter-console==6.0.0
    - markupsafe==1.1.1
    - metview==1.3.1
    - mistune==0.8.4
    - more-itertools==8.0.2
    - nbconvert==5.6.1
    - nbformat==4.4.0
    - notebook==6.0.2
    - pandas==0.25.3
    - pandocfilters==1.4.2
    - pickleshare==0.7.5
    - prometheus-client==0.7.1
    - prompt-toolkit==2.0.10
    - pycparser==2.19
    - pyrsistent==0.15.6
    - pytz==2019.3
    - pyzmq==18.1.1
    - qtconsole==4.6.0
    - send2trash==1.5.0
    - terminado==0.8.3
    - testpath==0.4.4
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - zipp==0.6.0
